# Example configuration file
# Copy this to config/local.yaml and edit as needed

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 4

# Security settings
security:
  secret_key: "your-secret-key-here"  # Change this!
  token_expiry: 3600  # 1 hour
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"

# Database settings
database:
  url: "postgresql://user:password@localhost:5432/wholesale"
  pool_size: 20
  max_overflow: 10
  echo: false

# Cache settings
cache:
  type: "redis"
  url: "redis://localhost:6379/0"
  ttl: 3600

# Plugin settings
plugins:
  zillow_data_source:
    enabled: true
    api_key: "your-zillow-api-key"  # Change this!
    rate_limit: 100
    cache_ttl: 3600
    timeout: 30

  property_valuation_model:
    enabled: true
    model_type: "advanced"  # basic or advanced
    model_path: "models/property_valuation"
    feature_engineering:
      use_market_features: true
      use_location_features: true
      use_property_features: true
    training:
      batch_size: 32
      epochs: 100
      validation_split: 0.2

  property_recommender:
    enabled: true
    recommendation_strategy: "hybrid"  # collaborative, content_based, or hybrid
    similarity_metrics:
      - "location"
      - "price"
      - "features"
    max_recommendations: 10
    min_similarity_score: 0.7
    feature_weights:
      location_weight: 0.3
      price_weight: 0.3
      features_weight: 0.2
      market_weight: 0.2

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/wholesale.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Service settings
services:
  market_analysis:
    update_interval: 3600  # 1 hour
    max_history: 90  # days
    metrics:
      - "median_price"
      - "price_trend"
      - "inventory_level"
      - "days_on_market"

  data_integration:
    batch_size: 100
    timeout: 30
    retry_count: 3
    retry_delay: 5

# Task orchestrator settings
task_orchestrator:
  max_workers: 10
  queue_size: 1000
  default_timeout: 300  # 5 minutes
  priorities:
    high: 1
    medium: 2
    low: 3

# Monitoring settings
monitoring:
  enabled: true
  metrics_port: 9090
  collect_interval: 60
  exporters:
    prometheus:
      enabled: true
    statsd:
      enabled: false
      host: "localhost"
      port: 8125

# Development settings
development:
  mock_data: false
  debug_plugins: false
  profile_endpoints: false
