# Local development configuration
server:
  host: "0.0.0.0"
  port: 8000
  debug: true
  workers: 1

security:
  secret_key: "dev-secret-key-change-in-production"
  token_expiry: 3600
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"

database:
  url: "postgresql://admin:admin123@db:5432/realestate"
  pool_size: 5
  max_overflow: 10
  echo: true

cache:
  type: "redis"
  url: "redis://redis:6379/0"
  ttl: 3600
  max_connections: 10
  socket_timeout: 5

analyzers:
  business_permits:
    enabled: true
    update_interval: 3600
    cache_ttl: 86400
  
  demographics:
    enabled: true
    update_interval: 86400
    cache_ttl: 604800
  
  transit:
    enabled: true
    update_interval: 3600
    cache_ttl: 86400
  
  crime_stats:
    enabled: true
    update_interval: 3600
    cache_ttl: 86400

ml_models:
  neighborhood_prediction:
    model_type: "neural_network"
    model_path: "models/neighborhood_prediction"
    batch_size: 32
    update_frequency: 604800
  
  property_valuation:
    model_type: "ensemble"
    model_path: "models/property_valuation"
    confidence_threshold: 0.85
    update_frequency: 86400

integrations:
  slack:
    enabled: true
    webhook_url: ""
  
  discord:
    enabled: true
    webhook_url: ""

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/realestate.log"
  max_size: 10485760
  backup_count: 5

development:
  mock_data: true
  debug_plugins: true
  profile_endpoints: true
