name: Performance Tests

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:  # Allow manual trigger

jobs:
  performance:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust pytest-benchmark

    - name: Run benchmark tests
      run: pytest tests/performance --benchmark-only --benchmark-json output.json

    - name: Run load tests
      run: |
        locust -f tests/performance/locustfile.py --headless -u 100 -r 10 --run-time 5m

    - name: Generate performance report
      run: python scripts/generate_performance_report.py

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: |
          output.json
          performance-report.html
          locust_stats.csv
